# Generated by Django 4.1.2 on 2022-11-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_club_alter_profile_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Клуб', 'verbose_name_plural': 'Список клубов'},
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название клуба'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.club'),
        ),
    ]
