# Generated by Django 4.1.2 on 2022-11-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_name_alter_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.club'),
        ),
    ]
